# Generated by Django 4.2.5 on 2023-10-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='logo',
            field=models.CharField(default='none', max_length=1000),
            preserve_default=False,
        ),
    ]
