# Generated by Django 4.2.5 on 2023-10-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='is_accepted',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
